### ISSUE TITLE
Please bump the plugin version in pelican-plugins repo

### ISSUE THREAD

**Issue by plaes** [ingwinlu/pelican-toc#7]
This plugin in pelican-plugins repository is outdated.

I was working on feature to pass toc tree structure to content so generated list could be customized and then discovered that it has already been implemented here.

**Comment by ingwinlu** [comment]
the plugin is added as a submodule for exactly this reason, so I don't have to PR everytime I make changes. Please read up on submodules and how to pull the latest version of one.
